import Head from "next/head"

import React from "react"

import { styled } from "@material-ui/core/styles"

import AppBar from "../components/AppBar"
import Menu from "../components/Menu"
import { CategoryChipPositionProvider } from "../components/CategoryChipPositionProvider"
import { CategoryInViewProvider } from "../components/CategoryInViewProvider"
import { CategoryAnchorProvider } from "../components/CategoryAnchorProvider"
import { MenuDataProvider } from "../components/MenuDataProvider"
import Footer from "../components/Footer"
import { AppBarStatusProvider } from "../components/AppBarStatusProvider"

const MenuWidthLimiter = styled("div")({
  maxWidth: 599,
  margin: "0 auto",
})

export default function Home() {
  return (
    <div style={{ backgroundColor: "white" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuWidthLimiter>
        <CategoryAnchorProvider>
          <CategoryChipPositionProvider>
            <CategoryInViewProvider>
              <MenuDataProvider>
                <AppBarStatusProvider>
                  <AppBar />
                  <Menu />
                  <Footer />
                </AppBarStatusProvider>
              </MenuDataProvider>
            </CategoryInViewProvider>
          </CategoryChipPositionProvider>
        </CategoryAnchorProvider>
      </MenuWidthLimiter>
    </div>
  )
}
