import Head from "next/head"

import React from "react"
import PropTypes from "prop-types"

import { styled } from "@material-ui/core/styles"
import {
  AppBar,
  Toolbar,
  Typography,
  CssBaseline,
  useScrollTrigger,
  Box,
  Slide,
  IconButton,
  Container,
} from "@material-ui/core"
import MenuIcon from "@material-ui/icons/Menu"
import Announcement from "../components/Announcement"
import SupplierAndCategory from "../components/SupplierAndCategory"
import { CategoryChipPositionProvider } from "../components/CategoryChipPositionProvider"
import { CategoryInViewProvider } from "../components/CategoryInViewProvider"
import { CategoryAnchorProvider } from "../components/CategoryAnchorProvider"
import { MenuDataProvider } from "../components/MenuDataProvider"
import Footer from "../components/Footer"

function HideOnScroll({ children }) {
  const trigger = useScrollTrigger()

  return (
    <Slide appear={false} direction="down" in={!trigger}>
      {children}
    </Slide>
  )
}

HideOnScroll.propTypes = {
  children: PropTypes.element.isRequired,
}

function HideAppBar({ children }) {
  return (
    <React.Fragment>
      <CssBaseline />
      <HideOnScroll>{children}</HideOnScroll>
      <Toolbar />
    </React.Fragment>
  )
}

const StyledAppBar = styled(AppBar)({
  backgroundColor: "white",
  color: "#454F5B",
  boxShadow: "none",
})

const StyledMenuIconButton = styled(IconButton)(({ theme }) => ({
  marginLeft: theme.spacing(0.5),
  marginRight: theme.spacing(2),
}))

const ShopTitle = styled(Typography)({
  textOverflow: "ellipsis",
  overflow: "hidden",
  whiteSpace: "nowrap",
})

const MenuWidthLimiter = styled("div")({
  maxWidth: 599,
  margin: "0 auto",
})

export default function Home() {
  return (
    <div style={{ backgroundColor: "white" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuWidthLimiter>
        <HideAppBar>
          <StyledAppBar>
            <Toolbar>
              <StyledMenuIconButton
                edge="start"
                color="inherit"
                aria-label="menu"
              >
                <MenuIcon />
              </StyledMenuIconButton>
              <ShopTitle variant="h6">門市訂貨賣場</ShopTitle>
            </Toolbar>
          </StyledAppBar>
        </HideAppBar>

        <Announcement
          title="公告"
          announcement="為提升各店家肉品及物料採購商品之效率，此公告將明列各品項物料現階段採購時程，以期各店能準時採購且準時收到貨品。 為提升各店家肉品及物料採購商品之效率，此公告將明列各品項物料現階段採購時程，以期各店能準時採購且準時收到貨品。"
          defaultExpanded={false}
        />

        <CategoryAnchorProvider>
          <CategoryChipPositionProvider>
            <CategoryInViewProvider>
              <MenuDataProvider>
                <SupplierAndCategory />
                <Footer />
              </MenuDataProvider>
            </CategoryInViewProvider>
          </CategoryChipPositionProvider>
        </CategoryAnchorProvider>
      </MenuWidthLimiter>
    </div>
  )
}
